version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: claude-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: claude
      POSTGRES_PASSWORD: claude123
      POSTGRES_DB: claude_test
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claude -d claude_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
    driver: local
